---
- name: Wordpress | Apache | Copy virtual host configuration file
  template:
    src: apache-vhost.conf.j2
    dest: "/etc/apache2/sites-available/{{ wp_sitename }}.conf"
    owner: root
    group: root
    mode: 0644

# - name: WordPress | Apache | Enable rewrite
#   apache2_module:
#     state: present
#     name: rewrite
#   notify: restart apache2

- name: Enable Apache mods.
  file:
    src: "/etc/apache2/mods-available/rewrite.load"
    dest: "/etc/apache2/mods-enabled/rewrite.load"
    state: link
  notify: restart apache2

- name: Remove default apache2 site.
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: restart apache2

- name: Activate custom Backuppc apache site.
  file:
    path: "/etc/apache2/sites-enabled/{{ wp_sitename }}.conf"
    src: "/etc/apache2/sites-available/{{ wp_sitename }}.conf"
    state: link
  notify: restart apache2
